<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="PC-f7ad11" failures="1" tests="4" name="Test1" time="24.606" errors="0" timestamp="2022-09-21T22:26:57 IST">
  <testcase classname="Task.Customer" name="createcustomer" time="1.811"/>
  <testcase classname="Task.Customer" name="createcustomer" time="2.656"/>
  <testcase classname="Task.Customer" name="createcustomer" time="3.256"/>
  <testcase classname="Task.Customer" name="createcustomer" time="1.762">
    <failure type="java.lang.AssertionError" message="expected [Customer &amp;quot;JP morgan 1&amp;quot; already exists. Please choose other customer name.] but found [Customer &amp;quot;JP morgan 1&amp;quot; has been successfully created.]">
      <![CDATA[java.lang.AssertionError: expected [Customer "JP morgan 1" already exists. Please choose other customer name.] but found [Customer "JP morgan 1" has been successfully created.]
at Task.Customer.createcustomer(Customer.java:42)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- createcustomer -->
  <testcase classname="Task.Customer" name="deletecustomer" time="0.0">
    <ignored/>
  </testcase> <!-- deletecustomer -->
</testsuite> <!-- Test1 -->
